---
version: '2'

services:

  letsencrypt-generic:
    image: csmith/letsencrypt-generic:latest
    container_name: autoproxy_letsencrypt-generic
    restart: always
    volumes:
      - letsencrypt-data:/letsencrypt
      - ../dns-hook-script:/run.sh
    environment:
      # - STAGING=yes
      - ACCEPT_CA_TERMS=yes
      - EMAIL=shane@mydnshost.co.uk

  nginx-updater:
    volumes:
      - ../docker-service-nginx_generate.py:/generate.py
      - ../nginx.tpl:/nginx.tpl
      - letsencrypt-data:/letsencrypt

  nginx:
    volumes:
      - ../nginx-default/:/usr/share/nginx/html/
