---
version: '2'

services:

  letsencrypt-http:
    image: csmith/letsencrypt-http-01:latest
    container_name: autoproxy_letsencrypt-http
    restart: always
    volumes:
      - letsencrypt-data:/letsencrypt
    environment:
      # - STAGING=yes
      - ACCEPT_CA_TERMS=yes
      - EMAIL=shane@mydnshost.co.uk

  nginx:
    volumes:
      - ../nginx-default/:/usr/share/nginx/html/
