---

version: '2.3'

services:
  proxy:
    command: --acme.email="<email>"
    labels:
      traefik.http.middlewares.proxy-auth.basicauth.users: "user:$$apr1$$MaV/E6fT$$vmOmd5I4TKc2O37If4MxM0"
      traefik.http.routers.proxy.rule: "Host:<VHOST>"

  static:
    labels:
      traefik.http.routers.static.rule: "Host:static.somehost"

  web:
    environment:
      - API_PUBLICURL=https://api.somehost/
      - RECAPTCHA_SITE=
      - RECAPTCHA_SECRET=
    labels:
      traefik.http.routers.web.rule: "Host:<VHOST>"

  api:
    labels:
      traefik.http.routers.api.rule: "Host:api.somehost"

  gmworker1:
    environment:
      - EMAIL_ENABLED=
      - EMAIL_SERVER=
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=
      - EMAIL_FROM=

  gmworker2:
    environment:
      - DUMMY_ENV=

  database:
    environment:
      - MYSQL_ROOT_PASSWORD=

  maintenance:
    environment:
      - API_URL=
      - API_DOMAIN=
      - API_RRNAMES=
      - API_DOMAINKEY=
      - STATUSCAKE_USER=
      - STATUSCAKE_APIKEY=
      - STATUSCAKE_TESTIDS=
      - INFLUX_BIND_SLAVES=

  bind:
    environment:
      - MASTER=
      - SLAVES=
      - RNDCKEY=
    ports:
      - 53:53/tcp
      - 53:53/udp

  chronograf:
    environment:
      - TOKEN_SECRET=SomeKindOfSecret
      - AUTH_DURATION=1h
      - GH_CLIENT_ID=
      - GH_CLIENT_SECRET=
      - GH_ORGS=
    labels:
      traefik.http.routers.chronograf.rule: "Host:<VHOST>"

  rabbitmq:
    labels:
      traefik.http.middlewares.rabbitmq-auth.basicauth.users: "user:$$apr1$$MaV/E6fT$$vmOmd5I4TKc2O37If4MxM0"
      traefik.http.routers.rabbitmq.rule: "Host:<VHOST>"
