---

version: '2'

services:
  web:
    image: mydnshost/mydnshost-frontend:latest
    container_name: mydnshost_web
    hostname: www
    domainname: mydnshost.co.uk
    environment:
      - SITE_NAME=MyDNSHost
      - API_URL=http://api/
      - TEMPLATE_THEME=default
      - MEMCACHED=sessions1:11211
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
      - sessions1
    labels:
      com.chameth.vhost: "dev.mydnshost.co.uk"
      com.chameth.proxy: "80"

  api:
    image: mydnshost/mydnshost-api:latest
    container_name: mydnshost_api
    hostname: api
    domainname: mydnshost.co.uk
    environment:
      - HOOKKEY=413B5DC9-BF59-4533-AF60-834A5BB549EC
      - DB_SERVER=database
      - DB_SERVER_TYPE=mysql
      - DB_SERVER_USERNAME=dnsapi
      - DB_SERVER_PASSWORD=dnsapi
      - DB_SERVER_DATABASE=dnsapi
      - EMAIL_ENABLED=false
      - EMAIL_SERVER=mysql
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=
      - EMAIL_FROM=dns@example.org
      - MEMCACHED=sessions1:11211
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - database
    volumes:
      - bind-data:/bind
      - ./api-config.local.php:/dnsapi/config.local.php
      - ./rndc_rndc.conf:/etc/bind/rndc.conf
    labels:
      com.chameth.vhost: "devapi.mydnshost.co.uk"
      com.chameth.proxy: "80"

  database:
    image: mysql:latest
    container_name: mydnshost_database
    hostname: database
    domainname: mydnshost.co.uk
    environment:
      - MYSQL_USER=dnsapi
      - MYSQL_PASSWORD=dnsapi
      - MYSQL_DATABASE=dnsapi
      - MYSQL_ROOT_PASSWORD=isukr7hgtistg
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mydnshost-internal
    labels:
      uk.co.mydnshost.maintenance.db.backup: "true"
      uk.co.mydnshost.maintenance.db.user: "dnsapi"
      uk.co.mydnshost.maintenance.db.pass: "dnsapi"
      uk.co.mydnshost.maintenance.db.dbs: "dnsapi"

  maintenance:
    build: ./maintenance/container
    container_name: mydnshost_maintenance
    hostname: maintenance
    domainname: mydnshost.co.uk
    restart: always
    environment:
      - HOOKKEY=413B5DC9-BF59-4533-AF60-834A5BB549EC
      - MEMCACHED=sessions1:11211
    volumes:
      - ./maintenance/output:/output
      - ./maintenance/scripts:/scripts
      - ./maintenance/crontab:/etc/cron.d/maintenance
      - /var/run/docker.sock:/var/run/docker.sock
      - bind-data:/bind
      - ./rndc_rndc.conf:/etc/bind/rndc.conf
    networks:
      - mydnshost-internal
    depends_on:
      - api
      
  sessions1:
    container_name: mydnshost_sessions1
    image: memcached:alpine
    hostname: sessions1
    domainname: mydnshost.co.uk
    restart: always
    networks:
      - mydnshost-internal
    ports:
      - "127.0.0.1:11211:11211"
    mem_limit: 1g
    command: memcached -m 1024m

  bind:
    image: mydnshost/mydnshost-bind:latest
    container_name: mydnshost_bind
    hostname: bind
    domainname: mydnshost.co.uk
    environment:
      - RUNMODE=MASTER
      - MASTER=1.1.1.1;
      - SLAVES=2.2.2.2; 3.3.3.3; 4.4.4.4;
      - RNDCKEY=DTngw5O8I5Axx631GjQ9pA==
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
    volumes:
      - bind-data:/bind
      - ./bind_rndc.conf:/etc/bind/rndc.controls.conf
    ports:
      - 53:53/tcp
      - 53:53/udp


volumes:

  db-data:

  bind-data:

networks:

  mydnshost-internal:

