---

version: '2.3'

services:
  logspout:
    image: bekt/logspout-logstash:latest
    restart: always
    container_name: mydnshost_logspout
    command: 'logstash://logger:5000?filter.labels=mydnshost.log:true'
    environment:
      - INACTIVITY_TIMEOUT=1m
    networks:
      - mydnshost-internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  logger:
    image: logstash:7.3.0
    restart: always
    container_name: mydnshost_logger
    command: -f /logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - mydnshost-internal
    volumes:
     - ./logstash/logstash.conf:/logstash.conf

  proxy:
    image: traefik:1.7
    container_name: mydnshost_proxy
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    labels:
      mydnshost.log: "true"
      traefik.frontend.auth.basic.users: "user:$$apr1$$MaV/E6fT$$vmOmd5I4TKc2O37If4MxM0"
      traefik.frontend.rule: "Host:traefik.dev.mydnshost.co.uk"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "traefik"
      traefik.port: "8090"
      traefik.enable: "true"

  static:
    image: pierrezemb/gostatic
    hostname: static
    command: -fallback web-error.html
    container_name: mydnshost_static
    restart: always
    networks:
      - mydnshost-internal
    volumes:
      - ./static-pages:/srv/http
    labels:
      mydnshost.log: "true"
      # I'd really like to not have this, but traefik won't let me
      # have a backend-only container it insists on having a matching frontend.
      # So here we are...
      traefik.frontend.rule: "Host:static.dev.mydnshost.co.uk"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "static"
      traefik.port: "8043"
      traefik.enable: "true"

  web:
    image: mydnshost/mydnshost-frontend:latest
    scale: 1
    hostname: www
    domainname: mydnshost.co.uk
    environment:
      - SITE_NAME=MyDNSHost
      - API_URL=http://api/
      - TEMPLATE_THEME=default
      - REDIS_HOST=redis
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
    volumes:
      - ./frontend-config.local.php:/dnsfrontend/config.local.php
    labels:
      mydnshost.log: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:dev.mydnshost.co.uk,www.dev.mydnshost.co.uk"
      traefik.frontend.redirect.regex: "^https?://www.([^/]*)/(.*)"
      traefik.frontend.redirect.replacement: "https://$${1}/$${2}"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "web"
      traefik.port: "80"
      traefik.frontend.errors.network.backend: "static"
      traefik.frontend.errors.network.query: "/web-error.html"
      traefik.frontend.errors.network.status: "500-599"

  api:
    image: mydnshost/mydnshost-api:latest
    scale: 1
    hostname: api
    domainname: mydnshost.co.uk
    environment:
      - DB_SERVER=database
      - DB_SERVER_TYPE=mysql
      - DB_SERVER_USERNAME=dnsapi
      - DB_SERVER_PASSWORD=dnsapi
      - DB_SERVER_DATABASE=dnsapi
      - REDIS_HOST=redis
      - INFLUX_HOST=influxdb
      - RABBITMQ_HOST=rabbitmq
      - MONGO_HOST=mongo
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - database
      - rabbitmq
    volumes:
      - bind-data:/bind
      - ./api-config.local.php:/dnsapi/config.local.php
      - ./rndc_rndc.conf:/etc/bind/rndc.conf
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      mydnshost.log: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:devapi.mydnshost.co.uk"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "api"
      traefik.port: "80"
      traefik.frontend.errors.network.backend: "static"
      traefik.frontend.errors.network.query: "/api-error.json"
      traefik.frontend.errors.network.status: "500-599"

  joblogger:
    image: mydnshost/mydnshost-joblogger:latest
    container_name: mydnshost_joblogger
    hostname: joblogger
    domainname: mydnshost.co.uk
    environment:
      - DB_SERVER=database
      - DB_SERVER_TYPE=mysql
      - DB_SERVER_USERNAME=dnsapi
      - DB_SERVER_PASSWORD=dnsapi
      - DB_SERVER_DATABASE=dnsapi
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
      - rabbitmq
    volumes:
      - ./api-config.local.php:/dnsapi/config.local.php
    labels:
      mydnshost.log: "true"

  containerlogger:
    image: mydnshost/mydnshost-containerlogger:latest
    container_name: mydnshost_containerlogger
    hostname: containerlogger
    domainname: mydnshost.co.uk
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGO_HOST=mongo
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
      - rabbitmq
    volumes:
      - ./api-config.local.php:/dnsapi/config.local.php

  dispatcher:
    image: mydnshost/mydnshost-dispatcher:latest
    container_name: mydnshost_dispatcher
    hostname: dispatcher
    domainname: mydnshost.co.uk
    environment:
      - DB_SERVER=database
      - DB_SERVER_TYPE=mysql
      - DB_SERVER_USERNAME=dnsapi
      - DB_SERVER_PASSWORD=dnsapi
      - DB_SERVER_DATABASE=dnsapi
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
      - rabbitmq
    volumes:
      - ./api-config.local.php:/dnsapi/config.local.php
    labels:
      mydnshost.log: "true"

  gmworker1:
    image: mydnshost/mydnshost-workers:latest
    container_name: mydnshost_gmworker1
    hostname: gmworker1
    domainname: mydnshost.co.uk
    environment:
      - DB_SERVER=database
      - DB_SERVER_TYPE=mysql
      - DB_SERVER_USERNAME=dnsapi
      - DB_SERVER_PASSWORD=dnsapi
      - DB_SERVER_DATABASE=dnsapi
      - EMAIL_ENABLED=false
      - EMAIL_SERVER=
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=
      - EMAIL_FROM=dns@example.org
      - REDIS_HOST=redis
      - INFLUX_HOST=influxdb
      - DNSSEC_DSKEY_FILES=/bind/keys
      - WORKER_WORKERS=*,-verify_2fa_push,-call_domain_hooks
      - RABBITMQ_HOST=rabbitmq
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
    volumes:
      - bind-data:/bind
      - ./api-config.local.php:/dnsapi/config.local.php
      - ./rndc_rndc.conf:/etc/bind/rndc.conf
    labels:
      mydnshost.log: "true"

  gmworker2:
    image: mydnshost/mydnshost-workers:latest
    container_name: mydnshost_gmworker2
    hostname: gmworker2
    domainname: mydnshost.co.uk
    environment:
      - DB_SERVER=database
      - DB_SERVER_TYPE=mysql
      - DB_SERVER_USERNAME=dnsapi
      - DB_SERVER_PASSWORD=dnsapi
      - DB_SERVER_DATABASE=dnsapi
      - WORKER_WORKERS=verify_2fa_push,call_domain_hooks
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
    volumes:
      - bind-data:/bind
      - ./api-config.local.php:/dnsapi/config.local.php
      - ./rndc_rndc.conf:/etc/bind/rndc.conf
    labels:
      mydnshost.log: "true"

  database:
    image: mysql:5.7
    container_name: mydnshost_database
    hostname: database
    domainname: mydnshost.co.uk
    environment:
      - MYSQL_USER=dnsapi
      - MYSQL_PASSWORD=dnsapi
      - MYSQL_DATABASE=dnsapi
      - MYSQL_ROOT_PASSWORD=isukr7hgtistg
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mydnshost-internal
    labels:
      mydnshost.log: "true"
      uk.co.mydnshost.maintenance.db.backup: "true"
      uk.co.mydnshost.maintenance.db.user: "dnsapi"
      uk.co.mydnshost.maintenance.db.pass: "dnsapi"
      uk.co.mydnshost.maintenance.db.dbs: "dnsapi"

  maintenance:
    image: mydnshost/mydnshost-maintenance:latest
    container_name: mydnshost_maintenance
    hostname: maintenance
    domainname: mydnshost.co.uk
    restart: always
    environment:
      - API_URL=https://api.mydnshost.co.uk/
      - API_DOMAIN=test.example.org
      - API_RRNAMES=foobar,bazqux
      - API_DOMAINKEY=SomeKey
      - STATUSCAKE_USER=SomeUser
      - STATUSCAKE_APIKEY=SomeKey
      - STATUSCAKE_TESTIDS=12345,67890
      - INFLUX_HOST=influxdb
      - INFLUX_BIND_SLAVES=ns1=1.1.1.1, ns2=2.2.2.2, ns3=3.3.3.3
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    volumes:
      - ./maintenance/output:/output
      - /var/run/docker.sock:/var/run/docker.sock
      - bind-data:/bind
    networks:
      - mydnshost-internal
    depends_on:
      - api
    labels:
      mydnshost.log: "true"

  bind:
    image: mydnshost/mydnshost-bind:latest
    container_name: mydnshost_bind
    hostname: bind
    domainname: mydnshost.co.uk
    environment:
      - RUNMODE=MASTER
      - MASTER=1.1.1.1;
      - SLAVES=2.2.2.2; 3.3.3.3; 4.4.4.4;
      - STATISTICS=any;
      - RNDCKEY=DTngw5O8I5Axx631GjQ9pA==
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
    volumes:
      - bind-data:/bind
      - ./bind_rndc.conf:/etc/bind/rndc.controls.conf
    labels:
      mydnshost.log: "true"

  influxdb:
    image: influxdb:alpine
    container_name: mydnshost_influxdb
    hostname: influxdb
    domainname: mydnshost.co.uk
    restart: always
    networks:
      - mydnshost-internal
    volumes:
      - influxdb-data:/var/lib/influxdb
    labels:
      mydnshost.log: "true"

  chronograf:
    image: chronograf:alpine
    container_name: mydnshost_chronograf
    hostname: chronograf
    domainname: mydnshost.co.uk
    restart: always
    networks:
      - mydnshost-internal
    volumes:
      - chronograf-data:/var/lib/chronograf
    environment:
      - TOKEN_SECRET=SomeKindOfSecret
      - AUTH_DURATION=1h
      - GH_CLIENT_ID=
      - GH_CLIENT_SECRET=
      - GH_ORGS=
      - INFLUXDB_URL=http://influxdb:8086/
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:chronograf.dev.mydnshost.co.uk"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "chronograf"
      traefik.port: "8888"
    labels:
      mydnshost.log: "true"

  redis:
    image: redis:latest
    container_name: mydnshost_redis
    hostname: redis
    domainname: mydnshost.co.uk
    restart: always
    networks:
      - mydnshost-internal
    volumes:
      - redis-data:/data
    labels:
      mydnshost.log: "true"

  mongo:
    image: mongo:latest
    container_name: mydnshost_mongo
    hostname: mongo
    domainname: mydnshost.co.uk
    restart: always
    networks:
      - mydnshost-internal
    volumes:
      - mongo-data:/data/db
    labels:
      mydnshost.log: "true"

  rabbitmq:
    image: rabbitmq:management
    container_name: mydnshost_rabbitmq
    hostname: rabbitmq
    domainname: mydnshost.co.uk
    restart: always
    networks:
      - mydnshost-internal
    volumes:
      - rabbitmq-log:/var/log/rabbitmq
      - rabbitmq-data:/var/lib/rabbitmq
    labels:
      traefik.frontend.auth.basic.users: "user:$$apr1$$MaV/E6fT$$vmOmd5I4TKc2O37If4MxM0"
      traefik.frontend.rule: "Host:rabbitmq.dev.mydnshost.co.uk"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "rabbitmq"
      traefik.port: "15672"
      traefik.enable: "true"
      mydnshost.log: "true"

volumes:

  db-data:

  bind-data:

  influxdb-data:

  chronograf-data:

  redis-data:

  mongo-data:

  rabbitmq-log:

  rabbitmq-data:

networks:

  mydnshost-internal:

