---

version: '2'

services:
  web:
    environment:
      - API_PUBLICURL=https://api.somehost/
      - RECAPTCHA_SITE=
      - RECAPTCHA_SECRET=
    labels:
      com.chameth.vhost: "<VHOST>"

  api:
    environment:
      - HOOKKEY=
      - EMAIL_ENABLED=
      - EMAIL_SERVER=
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=
      - EMAIL_FROM=
    labels:
      com.chameth.vhost: "api.somehost"

  gmworker1:
    environment:
      - HOOKKEY=
      - EMAIL_ENABLED=
      - EMAIL_SERVER=
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=
      - EMAIL_FROM=

  database:
    environment:
      - MYSQL_ROOT_PASSWORD=

  maintenance:
    environment:
      - HOOKKEY=
      - API_URL=
      - API_DOMAIN=
      - API_RRNAMES=
      - API_DOMAINKEY=
      - STATUSCAKE_USER=
      - STATUSCAKE_APIKEY=
      - STATUSCAKE_TESTIDS=
      - INFLUX_BIND_SLAVES=

  bind:
    environment:
      - MASTER=
      - SLAVES=
      - STATISTICS=
      - RNDCKEY=

  chronograf:
    environment:
      - TOKEN_SECRET=SomeKindOfSecret
      - AUTH_DURATION=1h
      - GH_CLIENT_ID=
      - GH_CLIENT_SECRET=
      - GH_ORGS=
    labels:
      com.chameth.vhost: "<VHOST>"
