---

version: '2.3'

services:
  proxy:
    image: traefik:1.7
    container_name: mydnshost_proxy
    restart: always
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    labels:
      traefik.frontend.auth.basic.users: "user:$$apr1$$MaV/E6fT$$vmOmd5I4TKc2O37If4MxM0"
      traefik.frontend.rule: "Host:traefik.dev.mydnshost.co.uk"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "traefik"
      traefik.port: "8090"
      traefik.enable: "true"

  static:
    image: pierrezemb/gostatic
    hostname: static
    command: -fallback web-error.html
    container_name: mydnshost_static
    restart: always
    networks:
      - mydnshost-internal
    volumes:
      - ./static-pages:/srv/http
    labels:
      # I'd really like to not have this, but traefik won't let me
      # have a backend-only container it insists on having a matching frontend.
      # So here we are...
      traefik.frontend.rule: "Host:static.dev.mydnshost.co.uk"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "static"
      traefik.port: "8043"
      traefik.enable: "true"

  web:
    image: mydnshost/mydnshost-frontend:latest
    scale: 1
    hostname: www
    domainname: mydnshost.co.uk
    environment:
      - SITE_NAME=MyDNSHost
      - API_URL=http://api/
      - TEMPLATE_THEME=default
      - REDIS_HOST=redis
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
    volumes:
      - ./frontend-config.local.php:/dnsfrontend/config.local.php
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:dev.mydnshost.co.uk,www.dev.mydnshost.co.uk"
      traefik.frontend.redirect.regex: "^https?://www.([^/]*)/(.*)"
      traefik.frontend.redirect.replacement: "https://$${1}/$${2}"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "web"
      traefik.port: "80"
      traefik.frontend.errors.network.backend: "static"
      traefik.frontend.errors.network.query: "/web-error.html"
      traefik.frontend.errors.network.status: "500-599"

  api:
    image: mydnshost/mydnshost-api:latest
    scale: 1
    hostname: api
    domainname: mydnshost.co.uk
    environment:
      - DB_SERVER=database
      - DB_SERVER_TYPE=mysql
      - DB_SERVER_USERNAME=dnsapi
      - DB_SERVER_PASSWORD=dnsapi
      - DB_SERVER_DATABASE=dnsapi
      - JOBSERVER_HOST=gearman
      - JOBSERVER_TYPE=gearman
      - REDIS_HOST=redis
      - INFLUX_HOST=influxdb
      - RABBITMQ_HOST=rabbitmq
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - database
      - rabbitmq
    volumes:
      - bind-data:/bind
      - ./api-config.local.php:/dnsapi/config.local.php
      - ./rndc_rndc.conf:/etc/bind/rndc.conf
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:devapi.mydnshost.co.uk"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "api"
      traefik.port: "80"
      traefik.frontend.errors.network.backend: "static"
      traefik.frontend.errors.network.query: "/api-error.json"
      traefik.frontend.errors.network.status: "500-599"

  dispatcher:
    image: mydnshost/mydnshost-api:latest
    container_name: mydnshost_dispatcher
    hostname: dispatcher
    domainname: mydnshost.co.uk
    environment:
      - DB_SERVER=database
      - DB_SERVER_TYPE=mysql
      - DB_SERVER_USERNAME=dnsapi
      - DB_SERVER_PASSWORD=dnsapi
      - DB_SERVER_DATABASE=dnsapi
      - REDIS_HOST=redis
      - JOBSERVER_HOST=gearman
      - JOBSERVER_TYPE=gearman
      - RABBITMQ_HOST=rabbitmq
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
      - rabbitmq
    volumes:
      - ./api-config.local.php:/dnsapi/config.local.php
    command: /dnsapi/dispatcher/JobDispatcher.php

  gmworker1:
    image: mydnshost/mydnshost-api:latest
    container_name: mydnshost_gmworker1
    hostname: gmworker1
    domainname: mydnshost.co.uk
    environment:
      - DB_SERVER=database
      - DB_SERVER_TYPE=mysql
      - DB_SERVER_USERNAME=dnsapi
      - DB_SERVER_PASSWORD=dnsapi
      - DB_SERVER_DATABASE=dnsapi
      - EMAIL_ENABLED=false
      - EMAIL_SERVER=
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=
      - EMAIL_FROM=dns@example.org
      - REDIS_HOST=redis
      - INFLUX_HOST=influxdb
      - DNSSEC_DSKEY_FILES=/bind/keys
      - JOBSERVER_HOST=gearman
      - JOBSERVER_TYPE=gearman
      - WORKER_WORKERS=*,-verify_2fa_push,-call_domain_hooks
      - RABBITMQ_HOST=rabbitmq
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
      - gearman
    volumes:
      - bind-data:/bind
      - ./api-config.local.php:/dnsapi/config.local.php
      - ./rndc_rndc.conf:/etc/bind/rndc.conf
    command: /dnsapi/tasks/TaskRunner.php

  gmworker2:
    image: mydnshost/mydnshost-api:latest
    container_name: mydnshost_gmworker2
    hostname: gmworker2
    domainname: mydnshost.co.uk
    environment:
      - DB_SERVER=database
      - DB_SERVER_TYPE=mysql
      - DB_SERVER_USERNAME=dnsapi
      - DB_SERVER_PASSWORD=dnsapi
      - DB_SERVER_DATABASE=dnsapi
      - JOBSERVER_HOST=gearman
      - JOBSERVER_TYPE=gearman
      - WORKER_WORKERS=verify_2fa_push,call_domain_hooks
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
      - gearman
    volumes:
      - bind-data:/bind
      - ./api-config.local.php:/dnsapi/config.local.php
      - ./rndc_rndc.conf:/etc/bind/rndc.conf
    command: /dnsapi/tasks/TaskRunner.php

  database:
    image: mysql:5.7
    container_name: mydnshost_database
    hostname: database
    domainname: mydnshost.co.uk
    environment:
      - MYSQL_USER=dnsapi
      - MYSQL_PASSWORD=dnsapi
      - MYSQL_DATABASE=dnsapi
      - MYSQL_ROOT_PASSWORD=isukr7hgtistg
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mydnshost-internal
    labels:
      uk.co.mydnshost.maintenance.db.backup: "true"
      uk.co.mydnshost.maintenance.db.user: "dnsapi"
      uk.co.mydnshost.maintenance.db.pass: "dnsapi"
      uk.co.mydnshost.maintenance.db.dbs: "dnsapi"

  maintenance:
    image: mydnshost/mydnshost-maintenance:latest
    container_name: mydnshost_maintenance
    hostname: maintenance
    domainname: mydnshost.co.uk
    restart: always
    environment:
      - API_URL=https://api.mydnshost.co.uk/
      - API_DOMAIN=test.example.org
      - API_RRNAMES=foobar,bazqux
      - API_DOMAINKEY=SomeKey
      - STATUSCAKE_USER=SomeUser
      - STATUSCAKE_APIKEY=SomeKey
      - STATUSCAKE_TESTIDS=12345,67890
      - INFLUX_HOST=influxdb
      - INFLUX_BIND_SLAVES=ns1=1.1.1.1, ns2=2.2.2.2, ns3=3.3.3.3
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./maintenance/output:/output
      - /var/run/docker.sock:/var/run/docker.sock
      - bind-data:/bind
    networks:
      - mydnshost-internal
    depends_on:
      - api

  bind:
    image: mydnshost/mydnshost-bind:latest
    container_name: mydnshost_bind
    hostname: bind
    domainname: mydnshost.co.uk
    environment:
      - RUNMODE=MASTER
      - MASTER=1.1.1.1;
      - SLAVES=2.2.2.2; 3.3.3.3; 4.4.4.4;
      - STATISTICS=any;
      - RNDCKEY=DTngw5O8I5Axx631GjQ9pA==
    restart: always
    networks:
      - mydnshost-internal
    depends_on:
      - api
    volumes:
      - bind-data:/bind
      - ./bind_rndc.conf:/etc/bind/rndc.controls.conf
    ports:
      - 53:53/tcp
      - 53:53/udp

  influxdb:
    image: influxdb:alpine
    container_name: mydnshost_influxdb
    hostname: influxdb
    domainname: mydnshost.co.uk
    restart: always
    networks:
      - mydnshost-internal
    volumes:
      - influxdb-data:/var/lib/influxdb

  chronograf:
    image: chronograf:alpine
    container_name: mydnshost_chronograf
    hostname: chronograf
    domainname: mydnshost.co.uk
    restart: always
    networks:
      - mydnshost-internal
    volumes:
      - chronograf-data:/var/lib/chronograf
    environment:
      - TOKEN_SECRET=SomeKindOfSecret
      - AUTH_DURATION=1h
      - GH_CLIENT_ID=
      - GH_CLIENT_SECRET=
      - GH_ORGS=
      - INFLUXDB_URL=http://influxdb:8086/
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:chronograf.dev.mydnshost.co.uk"
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.backend: "chronograf"
      traefik.port: "8888"

  redis:
    image: redis:latest
    container_name: mydnshost_redis
    hostname: redis
    domainname: mydnshost.co.uk
    restart: always
    networks:
      - mydnshost-internal
    volumes:
      - redis-data:/data

  gearman:
    image: artefactual/gearmand:latest
    container_name: mydnshost_gearman
    hostname: gearman
    domainname: mydnshost.co.uk
    command: --queue-type=redis --redis-server=redis
    depends_on:
      - redis
    restart: always
    networks:
      - mydnshost-internal

  rabbitmq:
    image: rabbitmq:latest
    container_name: mydnshost_rabbitmq
    hostname: rabbitmq
    domainname: mydnshost.co.uk
    restart: always
    networks:
      - mydnshost-internal

volumes:

  db-data:

  bind-data:

  influxdb-data:

  chronograf-data:

  redis-data:

networks:

  mydnshost-internal:

