defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.traefik]
    address = ":8090"
    compress = true

  [entryPoints.http]
    address = ":80"
    compress = true

  [entryPoints.https]
    address = ":443"
    compress = true

    [entryPoints.https.tls]
      compress = true
      sniStrict = true
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
      ]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedbydefault = false

[acme]
  entryPoint = "https"
  storage = "/acme.json"
  OnHostRule = true
  acmeLogging = true

  [acme.httpChallenge]
    entryPoint = "http"

[api]
  entryPoint = "traefik"
  dashboard = true

  [api.statistics]
    recentErrors = 100
